### ISSUE TITLE
CSS file organization

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#10]
My recommendation is also alphabetical! You have to have _some_ organization and for anything but a trivial file it is impossible to order linearly anything that you might think of as 'logical'. Certainly, you could never depend on a maintainer to intuit what you thought of as logical and follow your original pattern. But everyone understands alphabetical order!

So first order selectors alphabetically. If the `@media` variants only apply to one selector, put them after that selector as you have done. But sometimes you want to affect many selectors, in which case group the `@media` variants at the end of the file.

Within each selector, group the CSS properties alphabetically too. That can be a pain but VSCode has a nice [sort lines plugin](https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines).

**Comment by Alex-Rafter** [comment]
Can definitely see the value of ordering my CSS alphabetically. Have done this now using the plug-in. Thanks for the extension recommendation. 

I'm wondering though if some logical ordering still has a place - such as bunching * selectors, resets, and CSS variables, etc at the top before any alphabetical naming (if they aren't already in a separate file)? 

I know its not so relevant in this small project, but I'm feeling bit unsure about organising large amounts of css under one media query. I find it makes managing later changes somewhat difficult. For example, editing style changes for one element at various breakpoints means navigating up and down through the file because the selectors are buried in large lists ordered under specific media queries. Do you have any thoughts on this?  What do you think about sticking to the first part of your suggestion for all media query-based styles - always playing these directly below?

**Comment by mflorence99** [comment]
Yes, I don't disagree about keeping * selectors etc at the top, but alpha order still settles that for me as * comes before any letter! I shoud explain that I ignore the . prefix for a class name when ordering, Also, I put global CSS variables under :root:

```css
:root {
  --primary-color: red;
  --another-color: blue;
}
```
