### ISSUE TITLE
Optimization to consider

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#12]
It can be quite expensive to traverse the DOM to make changes, especially if you are manipulating many elements. You could make a nice optimization very simply, given that all you are changing is the font size.

First, remove the `font-size: 1rem;` property from the `letterForm` class (or `.grid p` selector, if you follow my [suggestion](https://github.com/Alex-Rafter/typeCurve/issues/11)) and add it to the `grid` class. Font size is inherited by child elements from their parent.

Next, change your HTML:

```html
<div id="theGrid" class="grid">
  ...
</div>
```

Now changing the font size is much simpler:

```js
const theGrid = document.querySelector('#theGrid');

function changeFontSize() {
  ...
  theGrid.style.fontSize = `${x}px`;
}
```

Using an `id` selector is a good idea because it strengthens the important implicit dependency the code has on the HTML. Maintainers might feel free to change class names and not notice that if they do so they'll break your code. But an ID is a definite signal that some code somewhere is going to use its value.

**Comment by Alex-Rafter** [comment]
This makes a lot of sense. I think i had got a bit mixed up when trying to follow a rule from the Airbnb css style guide of not using ids in my css  (https://github.com/airbnb/css#id-selectors) and ended up pretty much abandoning them altogether in my html and js also. Can definitely see how this is a nicer solution, and the js is cleaner too.

Following on from your suggestion, i’m also trying to be more intentional with using inherited styles first before getting more specific on any element in my css also so i got a double win from this one!

**Comment by mflorence99** [comment]
Good deal!
