### ISSUE TITLE
Ordering within JavaScript file

### ISSUE THREAD

**Issue by mflorence99** [Alex-Rafter/typeCurve#8]
It doesn't matter much in a small file but, as things get more complex, it gets harder and harder to organize things 'logically'. In my experience, it is best not to try.

Long ago I settled on alphabetical ordering for everything. So functions (or methods in classes) ordered alphabetically. Variables and constants the same.

```js
// just an example; these are no longer needed 
// @see per https://github.com/Alex-Rafter/typeCurve/issues/1
const bigScreen = 1500;
const smallScreen = 320;

let bigFont, smallFont;
```

That's very much taste, so take that suggestion as you like!

Global code is always very important so it is critical not to bury it. So in this case, I would put the `addEventListener` calls either before or after your functions. Before works because JavaScript hoists function declarations to the top of the file.

**Comment by Alex-Rafter** [comment]
Have made a few updatesd in branch 1 based on the suggestions. 

- The variables and constants have been re-worked now though as priorities of objects (notes on issue 1).

- The event listeners have been right up to after these and before the functions now.

- The dropping of logical ordering: I still feel a bit attached to trying to order logically but perhaps it's because my personal projects are so small as for it to not be an issue? At work js is not ordered logically as you say, and alphabetical ordering would definitely make sense in this case... Have followed this advice in my CSS though!

**Comment by mflorence99** [comment]
Good deal! There re ESLint rules BTW that enforce ordering alphabetically, if enabled
